apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apbio-web
  namespace: default
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - apbioapchemtutor.com
        - www.apbioapchemtutor.com
      secretName: apbio-cf-origin-tls
  rules:
    - host: apbioapchemtutor.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prod-eileen-services-service
                port:
                  number: 80
    - host: www.apbioapchemtutor.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prod-eileen-services-service
                port:
                  number: 80
