apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lorena-web
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - lorenateachesbrazilian.com
        - www.lorenateachesbrazilian.com
      secretName: lorenateachesbrazilian-com-tls
  rules:
    - host: lorenateachesbrazilian.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prod-lorena-services
                port:
                  number: 80
    - host: www.lorenateachesbrazilian.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prod-lorena-services
                port:
                  number: 80
