apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lorena-web-http
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`lorenateachesbrazilian.com`) || Host(`www.lorenateachesbrazilian.com`)
      kind: Rule
      services:
        - name: prod-lorena-services-service
          port: 80
      middlewares:
        - name: https-redirect
